project_id = "tztpqynhluetmatvnrvl"

[[functions.ai4bharat-translate]]
net = ["api.ai4bharat.org", "indictrans2-api.ai4bharat.org"]

[[functions.ai4bharat-transliterate]]
net = ["api.ai4bharat.org", "indictrans2-api.ai4bharat.org"]

[[functions.chitralekha-transliterate]]
net = ["api.ai4bharat.org"]

[[functions.chitralekha-voiceover]]
net = ["api.ai4bharat.org"]