// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tztpqynhluetmatvnrvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6dHBxeW5obHVldG1hdHZucnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDM0ODYsImV4cCI6MjA3NDMxOTQ4Nn0.sz1-Z-fWka7iEsmWwanO6hiT2FwamSVI1fTzjoJs1iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});